services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: webmarkers-php
    volumes:
      - ./app:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=webmarkers
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - webmarkers-network
    depends_on:
      - mysql

  webserver:
    image: nginx:alpine
    container_name: webmarkers-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webmarkers-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: webmarkers-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=webmarkers
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - webmarkers-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: webmarkers-phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
    networks:
      - webmarkers-network
    depends_on:
      - mysql

  yolo-api:
    build:
      context: .
      dockerfile: Dockerfile-python
    container_name: webmarkers-yolo-api
    ports:
      - "8000:8000"
    volumes:
      - ./python-api:/app
    environment:
      - PYTHONUNBUFFERED=1
      - FASTAPI_RELOAD=1
      - YOLO_CONFIG_DIR=/app/yolo-config
    networks:
      - webmarkers-network

networks:
  webmarkers-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local