FROM php:8.3-fpm

# 1. Instalacja zależności systemowych
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# 2. Instalacja Composera
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# 3. Automatyczna instalacja Laravela (jeśli folder jest pusty)
WORKDIR /var/www/html
COPY ./app /var/www/html
RUN if [ -z "$(ls -A /var/www/html)" ]; then \
        composer create-project laravel/laravel /var/www/html --remove-vcs; \
    fi

# 4. Ustawienie uprawnień
RUN chown -R www-data:www-data /var/www/html/storage \
    && chmod -R 775 /var/www/html/storage