FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libopenblas-dev \
    liblapack-dev \
    libx11-dev \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN mkdir -p /app/yolo-config && chmod 777 /app/yolo-config

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./python-api /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
