version: '3.8'

services:
  # PHP 8.3 + Laravel (edytowany w VSCode na hoście)
  app:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: webmarkers-php
    volumes:
      - ./app:/var/www/html  # Montowanie kodu Laravela z hosta
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=webmarkers
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - webmarkers-network
    depends_on:
      - mysql

  # Serwer Nginx
  webserver:
    image: nginx:alpine
    container_name: webmarkers-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html  # Współdzielony kod Laravela
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webmarkers-network
    depends_on:
      - app

  # Baza danych MySQL
  mysql:
    image: mysql:8.0
    container_name: webmarkers-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=webmarkers
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - webmarkers-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: webmarkers-phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
    networks:
      - webmarkers-network
    depends_on:
      - mysql

  # Python API (YOLO-NAS/FastAPI) - edytowany w VSCode na hoście
  yolo-api:
    build:
      context: .
      dockerfile: Dockerfile-python
    container_name: webmarkers-yolo-api
    ports:
      - "8000:8000"
    volumes:
      - ./python-api:/app  # Montowanie kodu Pythona z hosta
    environment:
      - PYTHONUNBUFFERED=1
      - FASTAPI_RELOAD=1  # Auto-reload dla developmentu
    networks:
      - webmarkers-network

# Sieć i wolumeny
networks:
  webmarkers-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local